name       : picom
version    : '9.1'
release    : 13
source     :
    - git|https://github.com/yshui/picom : v9.1
license    :
    - MIT
    - MPL-2.0
component  : desktop
summary    : A compositor for X11
description: |
    An X11 compositor which may be used for light or custom desktops, such as the MATE Desktop, or i3.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gl)
    - pkgconfig(libconfig)
    - pkgconfig(libdrm)
    - pkgconfig(libpcre)
    - pkgconfig(pixman-1)
    - pkgconfig(uthash)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcomposite)
    - pkgconfig(xfixes)
    - pkgconfig(xext)
    - asciidoc
    - libev-devel
replaces   :
    - compton
setup      : |
    %meson_configure -Dwith_docs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
