name       : compton
version    : 2017.04.30
release    : 1
source     :
    - git|https://github.com/chjj/compton.git : 316eac0613bf342ff91cc645a6c3c80e6b9083fb
license    : MIT
component  : desktop
summary    : A compositor for X11
description: |
    An X11 compositor which may be used for light or custom desktops, such as the
    MATE Desktop, or i3.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gl)
    - pkgconfig(libconfig)
    - pkgconfig(libdrm)
    - pkgconfig(libpcre)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xinerama)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
    - asciidoc
build      : |
    %make
install    : |
    %make_install
