name       : compton
version    : '7.3'
release    : 6
source     :
    - git|https://github.com/yshui/compton : v7.3
license    :
    - MIT
    - MPL-2.0
component  : desktop
summary    : A compositor for X11
description: |
    An X11 compositor which may be used for light or custom desktops, such as the MATE Desktop, or i3.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gl)
    - pkgconfig(libconfig)
    - pkgconfig(libdrm)
    - pkgconfig(libpcre)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(pixman-1)
    - pkgconfig(uthash)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcomposite)
    - pkgconfig(xfixes)
    - pkgconfig(x11)
    - asciidoc
    - libev-devel
setup      : |
    %meson_configure -Dbuild_docs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
