name       : compton
version    : 6.2
release    : 4
source     :
    - https://github.com/yshui/compton/archive/v6.2.tar.gz : 1333133ca9dfea768256c3fff8362d12a98b4d129e6ab1e56b1e630353f269bb
license    :
    - MIT
    - MPL-2.0
component  : desktop
summary    : A compositor for X11
description: |
    An X11 compositor which may be used for light or custom desktops, such as the MATE Desktop, or i3.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(gl)
    - pkgconfig(libconfig)
    - pkgconfig(libdrm)
    - pkgconfig(libpcre)
    - pkgconfig(libxdg-basedir)
    - pkgconfig(pixman-1)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcomposite)
    - pkgconfig(xfixes)
    - pkgconfig(x11)
    - asciidoc
    - libev-devel
setup      : |
    %meson_configure -Dbuild_docs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
